// lib/main.dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:isar/isar.dart';
import 'package:path_provider/path_provider.dart';

import 'app/router.dart';
import 'app/theme.dart';
import 'core/db/isar_service.dart';
import 'core/notifications/notification_service.dart';
import 'core/services/quote_service.dart';
import 'firebase_options.dart'; // generated by flutterfire configure

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Lock to portrait on phones; allow landscape on tablets
  await SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  // Transparent status bar, coloured nav bar
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.dark,
      systemNavigationBarColor: Colors.white,
      systemNavigationBarIconBrightness: Brightness.dark,
    ),
  );

  // Firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Local DB (Isar)
  final dir = await getApplicationDocumentsDirectory();
  await IsarService.init(dir.path);

  // Local notifications
  await NotificationService.init();

  runApp(
    const ProviderScope(
      child: BloomPlannerApp(),
    ),
  );
}

class BloomPlannerApp extends ConsumerWidget {
  const BloomPlannerApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(routerProvider);
    final themeMode = ref.watch(themeModeProvider);

    return MaterialApp.router(
      title: 'Bloom Planner',
      debugShowCheckedModeBanner: false,

      // ── Themes ──────────────────────────────────────────────
      theme: BloomTheme.light(),
      darkTheme: BloomTheme.dark(),
      themeMode: themeMode,

      // ── Routing ─────────────────────────────────────────────
      routerConfig: router,

      // ── Localisation ────────────────────────────────────────
      supportedLocales: const [
        Locale('en'),
        Locale('es'),
        Locale('fr'),
        Locale('de'),
        Locale('ja'),
      ],
    );
  }
}
